### ISSUE TITLE
Add analyzing tools/checks (automated quality checks)

### ISSUE THREAD

**Issue by DalderupMaurice** [nos/client#170]
## Context
To assure the quality of the project we should add some analyzing tools/checks

Domains + possible tools for these domains: 
- Dependency Management (Greenkeeper, Renovate,....)
- Code quality checker (Better code, Code Climate, ...)
- Testing (Coveralls, ....)

**Comment by DalderupMaurice** [comment]
As we do not have admin access I've assign this to you @mhuggins 😄 
we can discuss which tools here or on discord

**Comment by jeroenptrs** [comment]
If we can add it to the nos orga, I would opt for [Greenkeeper](https://github.com/marketplace/greenkeeper/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW41NTg=#pricing-and-setup) since it'll run baked into our CI, checking whether dep updates break our tests or not.

For coverage, coveralls is nice but I'd love to look into Codecov as well.

@deanpress @mhuggins I'm not sure if you're into using them, but I think something like Sentry or Rollbar might be interesting for error monitoring. I think - especially for a big app as ours that needs to be robust and stable - this is a must.

**Comment by DalderupMaurice** [comment]
If we've chosen tools - I'd suggest we persist this on all repo's 
It's good to keep the starter kit templates etc up-to-date as well

**Comment by jeroenptrs** [comment]
Aside from setting up codecov, I think we're done here. Closing.
