### ISSUE TITLE
Track application errors

### ISSUE THREAD

**Issue by mhuggins** [nos/client#221]
## Expected Behavior
When errors occur in the app or the application crashes, we want it to be reported.

## Current Behavior
When errors occur in the app, we are not notified about it in any way.

## Possible Solution
A couple options worth considering:

* [electron crashReporter](https://github.com/electron/electron/blob/master/docs/api/crash-reporter.md) - This only tracks app crashes and depends on us setting up a web server that listens for reports.
* [sentry](https://sentry.io/welcome/) - This tracks app crashes as well as anything else we explicitly specify within the app.  This should be easy to setup with the help of [sentry-electron](https://github.com/getsentry/sentry-electron), but has a [monthly cost](https://sentry.io/pricing/).

## Steps to Reproduce (for bugs)
1. Crash the app or cause an error in the app
2. Don't receive a report.

## Context
We want to ensure the user experience matches our expectations.  Tracking errors will help improve the app over time.

## Your Environment
* Version used: 0.2.0
* Environment name and version: Any
* Operating System and version: Desktop

**Comment by Stabbz** [comment]
@mhuggins Hey, I can help out with this, how do you expect to receive and read the error reports?
Is email an option? 
Otherwise you would need some sort of back-end (web server) to receive and store errors. I can set-up a simple web server that would take in the POST requests that electron crashReporter sends and store them in any format you like.

Let me know if this is something that would interest you guys :)
