### ISSUE TITLE
Sending an asset resets the client. Transactions thereafter work.

### ISSUE THREAD

**Issue by deanpress** [nos/client#340]
## Expected Behavior
When you send an asset, the client shouldn't reset.

## Current Behavior
After launching the client, sending an asset using the wallet causes the client to reset. If you log in again during that client session, the transaction will work.

![nos send reset issue](https://user-images.githubusercontent.com/31391056/43013889-9c53cac0-8c4a-11e8-861b-e16cbbd72d01.gif)

## Steps to Reproduce
1. Start client
2. Log in
3. Send asset
4. Client restarts
5. Send asset again

## Your Environment
* nOS Client version used: develop/latest
* Operating System and version (desktop or mobile): Tested on Linux Mint 18 and Windows 10

**Comment by mhuggins** [comment]
Thanks for adding this. 👍

**Comment by mhuggins** [comment]
Did a little digging tonight and found that the initial URL is `http://localhost:9080/index.html#/login`, and as soon as the confirmation dialog is displayed, the user is redirected to `http://localhost:9080/index.html?`.  The second time around, since the URL already has an empty query string, it doesn't end up redirecting anywhere.

Something is redirecting to the same route but with an empty query string, which is effectively causing the page to reload.

**Comment by mhuggins** [comment]
To simplify, the redirect is going from `http://localhost:9080/index.html` to `http://localhost:9080/index.html?`.

**Comment by mhuggins** [comment]
One option as a hacky workaround is to make the site load with the `?` already appended.

**Comment by Mickieki** [comment]
5577555108112769

2561-09-09 15:28 GMT+07:00, Maurice Dalderup <notifications@github.com>:
