### ISSUE TITLE
Permit all invocations of this type on this contract

### ISSUE THREAD

**Issue by mhuggins** [nos/client#363]
## Describe the solution you'd like and the expected behavior
When a user is prompted to permit an invocation, provide a checkbox to "always permit this action for this contract".  If the user ticks the checkbox before approving the modal, then future invocations that will have prompt should instead be automatically approved.

## Is your feature request related to a problem? Please describe.
There are some types of invocations that a user might always trust.  An example would be invoking a "sendMessage" transaction in a chat app.  Having to approve every single message being delivered via nOS would make this cumbersome.

<img width="919" alt="screen shot 2018-07-28 at 9 36 45 am" src="https://user-images.githubusercontent.com/169093/43357613-0cb0beb8-924a-11e8-9518-db517d3cc943.png">

## Possible implementation / References
User setting should be saved in local storage.

The option to always approve invocations should be for a specific command on a specific smart contract (hash) on a specific network (e.g.: TestNet).  If any of these three items does not match on a subsequent invocation request, then the user should still be prompted (and in turn given the option to auto-approve that invocation command as well).

Invocation occurs via the components under `src/renderer/browser/components/RequestsProcessor/Invoke`.  The `index.js` container will need to be modified to automatically approve via `onConfirm` and render immediately (to prevent chaining children in the HOC).  That logic will need to appear before the `withPrompt` HOC is called.

## Additional context
nOS should be secure, but also convenient.

**Comment by deanpress** [comment]
Base URLs also need to be factored in for whitelisting invocations (e.g. `nos://neochat.neo`), otherwise bad actors hosted elsewhere have the opportunity to send invocations to a whitelisted address on behalf of the user.

We can also let users specify a maximum amount of assets attached to a whitelisted dApp before being prompted. Imagine a poker game; you don't want to have to be prompted each time you bet/call.

**Comment by mhuggins** [comment]
Good addition @deanpress.

**Comment by deanpress** [comment]
There are some other security considerations to make.

What if the user whitelists a smart contract that calls a function in another smart contract? What if that 2nd smart contract address is later changed to a malicious contract?

**Comment by mhuggins** [comment]
> What if the user whitelists a smart contract that calls a function in another smart contract? What if that 2nd smart contract address is later changed to a malicious contract?

I'm not sure what we can do in that scenario.  The scripthash for the original contract would not have changed, so no new approval would be needed.  The only thing I can think of that we could possibly do is parse the script for the contract itself, determine if it invokes other contracts, recurse, and maintain that list.  That would have to be stored along with the other data, and if that ever changes, then the user would be prompted again.

If a contract uses another contract, etc. 5-10 levels deep, then it could take a very long time between the dapp requesting user approval and the user actually seeing the approval dialog.  At least that would be true for the first time where each contract would have to be looked up in sequence.  On subsequent requests, all contracts could be fetched in parallel since we'd have the hashes at that point, and could simply check if any changed at that point.

**Comment by shashank-ezdiagno** [comment]
I would like to suggest an improvement for the way invocations are done.
Invocations usually cost gas and the user might not be aware that it takes some time between invocation and the reflection of results. So, the user might try to make the same invocation multiple times. In order to save gas and possibly prevent bots:

1. There should be a rate-limit on the number of invocations that can be made per unit time.
2. Prevent multiple successive invocations of the smart contract with same parameters.
3. There should be a way so that a developer can update the info on the UI when the transaction is confirmed on blockchain. Not sure how this can be done - maybe websockets. This will prevent the multiple testinvocation calls to query whether the state has been updated.

**Comment by mhuggins** [comment]
Adding a note that any invocation w/ attached assets should *never* be automatically approved.
