### ISSUE TITLE
Account zero-state

### ISSUE THREAD

**Issue by mhuggins** [nos/client#408]
## Describe the solution you'd like and the expected behavior
When the account has no NEO/GAS assets or NEP5 tokens, it should display a zero-state for clarity.  Additionally, the "Token to send" dropdown within the "Send" tab should display "No tokens available".

## Is your feature request related to a problem? Please describe.
Zero states help to provide insight regarding functionality that exists even though it's not currently accessible.

## Possible implementation / References
N/A

## Additional context
![Screen Shot 2018-08-05 at 9.34.37 AM.png](https://images.zenhubusercontent.com/5b2e57c502104679709f396f/9387ff2d-da15-4d73-b625-0a8beafbee13)

**Comment by fabric-8** [comment]
@mhuggins Wanted to look into that but since I'm not super pro with react – Could you help me get started? IE I'm not sure what approach should be taken: 

- Create a "ZeroState" component which gets rendered based on certain conditions?
- Should all of the existing components in the panel have a zero state? This seems somewhat messy to manage as the zero state gets fragmented across many places, making it (at least to me) harder to manage and style.

Would also have no idea how to properly set up the "zerostate" conditionals correctly.

Feel free to let me know if you think I'm not that much of a help in this case, but happy to jump in at least with the styling / visual side of things if that helps and learn a bit on the way :)

**Comment by mhuggins** [comment]
This one feels pretty development-heavy.  It's not very straightforward in that sense, especially if you've not done anything in the code yet.  Is it something that you want to get involved in on the development side?  If so, I'm happy to help walk through the process, but it's otherwise not something that I would go about assigning to a designer. 😄

**Comment by jeroenptrs** [comment]
If feel like we could split this up in logic and graphics, with @mhuggins taking the business logic side and @fabric-8 taking the presentational side (styling, animations, ...) to speed up the implementation :)

**Comment by DalderupMaurice** [comment]
We actually did assign @fabric-8 to it, hence his question :P 
It would be better to split it up as @jeroenptrs stated

**Comment by mhuggins** [comment]
@fabric-8 I just pushed up a new branch called `feat/account-loading` that includes some changes to help implement these designs.  The designs are partially implemented, but could use some cleanup.  The biggest thing missing is a loading state for the send/receive/transactions panel on the right.  (See the screenshot in #748.)

The three places where you'll specifically want to look are:

* BreakdownLoading.js / .scss
* HoldingsLoading.js / .scss
* TransactionsLoading.js / .scss

**Comment by fabric-8** [comment]
@mhuggins Awesome looking into it

**Comment by fabric-8** [comment]
Had a deeper look, tweaked things a bit by adding some animations and would like to propose the following:

I think there's no need to do a skeleton view for the transactions panel since we can display it right away with one tiny exception (token which is displayed/selected in the inputs: We could simply put nOS in there). 
We can then apply a disabled state to all elements within the transactions panel while things are being loaded.

To better see things in perspective/comparison, the different states can be seen here: https://www.figma.com/file/apqKpVZZDzppAb0lVH69iiZn/nOS-Client?node-id=107%3A2893

Happy to hear ya thoughts!

![loading-funds](https://user-images.githubusercontent.com/4112698/49929975-f8bcca00-fec3-11e8-827d-0d403a213411.gif)

![wallet_loading](https://user-images.githubusercontent.com/4112698/49929984-fd817e00-fec3-11e8-86ca-859973ef534c.png)
