### ISSUE TITLE
Electron container is not draggable

### ISSUE THREAD

**Issue by jeroenptrs** [nos/client#95]
I'm unable to drag the client, so moving it to other windows without using some osx shortcuts is impossible

**Comment by GwendalBrossard** [comment]
It is a known issue when the developer tools are opened (https://github.com/electron/electron/issues/3647). 
"A workaround for those that are affected by this long standing bug - if you hover the mouse over the top edge of the window until you see a resize cursor and then hold and drag to the side instead of up and down to resize it will let you move the window."

**Comment by DalderupMaurice** [comment]
Can this be closed? @jeroenptrs

**Comment by DalderupMaurice** [comment]
@jeroenptrs bump - what's the status on this? Can it be closed?

**Comment by mhuggins** [comment]
It's only draggable from the browser view right now (once logged in).  I feel like we should revisit drag & drop, but it probably doesn't make sense until we have a legit design to work again.  I say we close this for now and circle back at that point.
